"""
simulation.py
Discrete-Event Warehouse Execution Simulation.
Runs both Baseline (unregulated release) and Controlled (wave-release managed) simulations.
Accurately records timestamps, aisle occupancy, waiting times, and travel distances.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Any, Optional
from src.data_generator import DEFAULT_AISLES, calculate_grid_distance, calculate_path_total_distance
from src.congestion import calculate_congestion, classify_congestion
from src.controller import wave_release_controller


class WarehouseSimulation:
    def __init__(
        self,
        orders_df: pd.DataFrame,
        aisles_def: Optional[Dict] = None,
        controlled: bool = False,
        safe_threshold: float = 75.0,
        sensor_available: bool = True,
        fallback_congestion: float = 60.0,
        retry_delay_seconds: float = 30.0,
        walking_speed_mps: float = 1.0
    ):
        """
        Initializes the warehouse execution simulation.

        Parameters:
        - orders_df: Synthetic dataset generated by data_generator
        - aisles_def: Warehouse layout definition dictionary
        - controlled: If True, applies wave_release_controller; if False, baseline uncontrolled release
        - safe_threshold: Safe congestion threshold percentage
        - sensor_available: Sensor health boolean
        - fallback_congestion: Fallback congestion % if sensor fails
        - retry_delay_seconds: Time to delay a worker when wave-release holds them
        - walking_speed_mps: Worker walking speed in meters per second (default: 1.0 m/s)
        """
        self.raw_df = orders_df.copy()
        self.aisles_def = aisles_def if aisles_def is not None else DEFAULT_AISLES
        self.controlled = controlled
        self.safe_threshold = safe_threshold
        self.sensor_available = sensor_available
        self.fallback_congestion = fallback_congestion
        self.retry_delay_seconds = retry_delay_seconds
        self.walking_speed = walking_speed_mps

        # Results tracking
        self.executed_orders: List[Dict[str, Any]] = []
        self.aisle_intervals: Dict[str, List[Tuple[float, float, str]]] = {
            a: [] for a in self.aisles_def.keys()
        }
        self.controller_logs: List[Dict[str, Any]] = []

    def _get_current_workers_in_aisle(self, aisle: str, current_time: float) -> int:
        """Counts how many workers are physically inside the given aisle at current_time."""
        count = 0
        for entry_t, exit_t, _ in self.aisle_intervals.get(aisle, []):
            if entry_t <= current_time < exit_t:
                count += 1
        return count

    def run(self) -> pd.DataFrame:
        """
        Executes the simulation across all orders in chronological request order.
        Returns a DataFrame of completed order execution metrics.
        """
        # Group raw rows by order_id to extract unique order profiles
        order_groups = self.raw_df.groupby("order_id", sort=False)
        order_list = []

        for order_id, group in order_groups:
            first_row = group.iloc[0]
            # List of aisles from the path
            path_aisles = [r["aisle_id"] for _, r in group.sort_values("path_step").iterrows()]
            pick_times = [r["pick_time"] for _, r in group.sort_values("path_step").iterrows()]
            total_dist = first_row["distance_m"]
            req_release_time = first_row["release_time"]
            worker_id = first_row["worker_id"]

            order_list.append({
                "order_id": order_id,
                "worker_id": worker_id,
                "req_release_time": req_release_time,
                "path": path_aisles,
                "pick_times": pick_times,
                "total_dist": total_dist,
            })

        # Sort orders by requested release time
        order_list.sort(key=lambda x: x["req_release_time"])

        # Process each order
        for item in order_list:
            order_id = item["order_id"]
            worker_id = item["worker_id"]
            req_time = item["req_release_time"]
            path = item["path"]
            pick_times = item["pick_times"]
            total_dist = item["total_dist"]

            target_first_aisle = path[0]
            aisle_cap = self.aisles_def[target_first_aisle]["capacity"]

            actual_release_time = req_time
            delay_count = 0

            # If controlled mode is enabled, evaluate wave-release controller
            if self.controlled:
                max_retries = 20  # Prevent infinite hold
                for _ in range(max_retries):
                    current_workers = self._get_current_workers_in_aisle(
                        target_first_aisle, actual_release_time
                    )
                    ctrl_decision = wave_release_controller(
                        congestion_percentage=None,
                        requested_workers=1,
                        safe_threshold=self.safe_threshold,
                        aisle_capacity=aisle_cap,
                        current_workers=current_workers,
                        sensor_available=self.sensor_available,
                        fallback_congestion=self.fallback_congestion
                    )
                    ctrl_decision["order_id"] = order_id
                    ctrl_decision["timestamp"] = actual_release_time
                    ctrl_decision["target_aisle"] = target_first_aisle
                    self.controller_logs.append(ctrl_decision)

                    if ctrl_decision["decision"] == "ALLOW":
                        break
                    else:
                        # Delay worker release
                        actual_release_time += self.retry_delay_seconds
                        delay_count += 1

            waiting_time = max(0.0, actual_release_time - req_time)

            # Simulate worker traversal and picking through the path
            current_time = actual_release_time
            # Travel from depot (0,0) to first aisle
            first_coord = self.aisles_def[path[0]]["grid"]
            depot_travel_m = (abs(first_coord[0]) + abs(first_coord[1])) * 15.0
            current_time += depot_travel_m / self.walking_speed

            for step, aisle in enumerate(path):
                p_time = pick_times[step]
                entry_time = current_time
                exit_time = entry_time + p_time

                # Record physical occupancy interval for this aisle
                self.aisle_intervals[aisle].append((entry_time, exit_time, worker_id))

                current_time = exit_time
                if step < len(path) - 1:
                    leg_dist = calculate_grid_distance(aisle, path[step + 1], self.aisles_def)
                    current_time += leg_dist / self.walking_speed

            completion_time = current_time

            self.executed_orders.append({
                "order_id": order_id,
                "worker_id": worker_id,
                "requested_release_time": req_time,
                "actual_release_time": actual_release_time,
                "waiting_time": waiting_time,
                "delay_count": delay_count,
                "completion_time": completion_time,
                "turnaround_time": completion_time - req_time,
                "path_length": len(path),
                "total_distance_m": total_dist,
                "mode": "CONTROLLED" if self.controlled else "BASELINE"
            })

        return pd.DataFrame(self.executed_orders)

    def get_aisle_congestion_timeseries(
        self,
        time_step_seconds: float = 30.0
    ) -> pd.DataFrame:
        """
        Samples aisle congestion percentage across the entire simulation duration.
        Returns a DataFrame indexed by time step with columns for each aisle.
        """
        if not self.executed_orders:
            return pd.DataFrame()

        max_time = max(r["completion_time"] for r in self.executed_orders)
        timestamps = np.arange(0, max_time + time_step_seconds, time_step_seconds)

        records = []
        for t in timestamps:
            row: Dict[str, Any] = {"timestamp_sec": t}
            for aisle, info in self.aisles_def.items():
                workers = self._get_current_workers_in_aisle(aisle, t)
                cap = info["capacity"]
                cong = calculate_congestion(workers, cap, self.sensor_available, self.fallback_congestion)
                row[f"{aisle}_workers"] = workers
                row[f"{aisle}_congestion"] = cong
                row[f"{aisle}_level"] = classify_congestion(cong)
            records.append(row)

        return pd.DataFrame(records)
